name: Deploy Website

on:
  push:
    branches: [main]
  # This allows the Blog Repo to trigger this workflow remotely
  repository_dispatch:
    types: [update_blog]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 1. Entra na pasta portfolio para instalar
      - name: Install Dependencies
        run: npm ci
        working-directory: ./portfolio

      # 2. Entra na pasta portfolio para criar o site
      - name: Build Static Site
        run: npm run build
        working-directory: ./portfolio
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      # 3. Faz o Upload (Note que o caminho mudou para incluir portfolio/)
      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./portfolio/out/    # <--- MUDANÃ‡A IMPORTANTE AQUI
          server-dir: ./public_html/
